apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
  ports:
    - name: http
      appProtocol: http
      port: 8080
